name: Install uv, rust, and python
description: Install uv, rust, and python
inputs:
  python_version:
    description: The version of python to install
    required: false
    default: '3.10'
runs:
  using: composite
  steps:
  - name: Install rust
    shell: bash
    run: |
      CARGO_BIN="$HOME/.cargo/bin"
      if command -v rustup > /dev/null 2>&1; then
        echo "rustup already installed: $(rustup --version | head -n1)"
      else
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      fi
      echo "$CARGO_BIN" >> $GITHUB_PATH
  - name: Install uv
    shell: bash
    run: |
      UV_BIN="$HOME/.local/bin"
      if command -v uv > /dev/null 2>&1; then
        echo "uv already installed: $(uv --version)"
      else
        curl -LsSf https://astral.sh/uv/install.sh | sh
      fi
      echo "$UV_BIN" >> $GITHUB_PATH
  - name: Install (and pin) python version ${{ inputs.python_version }}
    shell: bash
    run: |
      PYTHON_BIN="python${{ inputs.python_version }}"
      if command -v "$PYTHON_BIN" > /dev/null 2>&1; then
        "$PYTHON_BIN" --version
      else
        uv python install ${{ inputs.python_version }}
      fi
